# .bashrc

# User specific aliases and functions

alias rm='rm -i'
alias cp='cp -i'
alias mv='mv -i'

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

# these are dummy values, obviously
export UPLOADHOST=UPLOADHOST
export DVAPIKEY=DVAPIKEY
export DVHOSTINT=DVHOSTINT
export DVHOST=DVHOST
